<?php
require('fpdf/fpdf.php');

class PDF extends FPDF
{
    // Header section
    function Header()
    {
        $this->Image('images/logo.png', 10, 8, 25); // Local image recommended
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(80);
        $this->Cell(30, 10, 'Service Invoice', 0, 0, 'C');
        $this->Ln(20);
    }

    // Footer section
    function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by Vehicle Service Management System', 0, 0, 'C');
    }
}

// Create PDF
$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 12);

// Sample data from POST or DB
$invoiceData = [
    'customer_name' => $_POST['customer_name'] ?? 'John Doe',
    'vehicle_model' => $_POST['vehicle_model'] ?? 'Honda City',
    'service_date' => $_POST['service_date'] ?? '2025-10-30',
    'service_type' => $_POST['service_type'] ?? 'Full Body Service',
    'total_amount' => $_POST['total_amount'] ?? '₹8,500'
];

// Header Info
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 10, 'Customer Name: ' . $invoiceData['customer_name'], 0, 1);
$pdf->Cell(0, 10, 'Vehicle Model: ' . $invoiceData['vehicle_model'], 0, 1);
$pdf->Cell(0, 10, 'Service Date: ' . $invoiceData['service_date'], 0, 1);
$pdf->Cell(0, 10, 'Service Type: ' . $invoiceData['service_type'], 0, 1);
$pdf->Cell(0, 10, 'Total Amount: ' . $invoiceData['total_amount'], 0, 1);

$pdf->Ln(10);
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'Service Images', 0, 1, 'C');
$pdf->Ln(5);

// ✅ Example: Displaying uploaded images with descriptions
$uploadedImages = [
    ['path' => 'uploads/image1.jpg', 'desc' => 'Front Bumper Damage Before Repair'],
    ['path' => 'uploads/image2.jpg', 'desc' => 'Front Bumper After Repair'],
    ['path' => 'uploads/image3.jpg', 'desc' => 'Final Wash and Polish Completed']
];

foreach ($uploadedImages as $img) {
    if (file_exists($img['path'])) {
        $pdf->Image($img['path'], null, null, 80, 60);
        $pdf->Ln(62); // spacing after image
        $pdf->SetFont('Arial', 'I', 11);
        $pdf->Cell(0, 10, $img['desc'], 0, 1, 'C');
        $pdf->Ln(5);
    }
}

$pdf->Ln(10);
$pdf->SetFont('Arial', '', 11);
$pdf->MultiCell(0, 8, "Note: This invoice includes detailed before-and-after service images for better transparency and customer trust.\nThank you for choosing our service!", 0, 'L');

$pdf->Output('I', 'Invoice.pdf');
?>
